version: '3'

services:
  spa:
    image: ghcr.io/archivedc/single-page-archiver:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /home/doe/archives:/var/www/html/data
      # - ./_config.php:/var/www/html/_config.php:ro
    ports:
      - 80:80
    restart: unless-stopped

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: spa
      MYSQL_USER: spa
      MYSQL_PASSWORD: spa
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
