version: '3'

services:
  spa:
    image: ghcr.io/archivedc/single-page-archiver:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /home/doe/archives:/var/www/html/data:ro
      # - ./_config.php:/var/www/html/_config.php:ro
    ports:
      - 80:80
    restart: unless-stopped
